---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
          - prettier-plugin-sort-json

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.1"
    hooks:
      - id: ruff
        args:
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.7.0
    hooks:
      - id: cspell
        name: Spell check with cspell

  - repo: https://github.com/terrencepreilly/darglint.git
    rev: v1.8.1
    hooks:
      - id: darglint

  - repo: https://github.com/pycqa/pylint.git
    rev: v3.1.0
    hooks:
      - id: pylint
        args:
          - --output-format=colorized
        additional_dependencies:
          - configargparse
          - pytest
          - requests
          - ruamel.yaml
          - single_source

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
          - types-colorama
          - types-Pygments
          - types-requests
          - types-setuptools
        args:
          - --python-version=3.10
        pass_filenames: false
