dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  # All dot files in the root
  - \.*
  # This file
  - cspell.config.yaml
  # The shared file for tool configuration
  - pyproject.toml
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - "/^\\s*```[\\s\\S]*?^\\s*```/gm"
